name: Tests
on: 
  workflow_dispatch:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Run docker compose
      run: docker-compose up --abort-on-container-exit --force-recreate
